### ISSUE TITLE
Error on "creature_template.sql" 

### ISSUE THREAD

**Issue by chachecete** [pangolp/mod-npc-promotion#2]
Query: INSERT INTO `creature_template` (`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `Kill...

Error Code: 1054
Unknown column 'mindmg' in 'field list'

**Comment by pangolp** [comment]
Hi. The SQL script may be out of date. The problem, is that when I created the module, the table structure was one and then over time it changed. It is normal that this happens with modules. There is a solution, which is to accommodate the repository folders and then with the azerothcore db_assembler, it should work, but you would have to apply the base, then custom and finally the updates of the world table.

**Comment by chachecete** [comment]
I make a pull request with modifications on the creature_template.sql. Can you check it out?. Thank you.

**Comment by pangolp** [comment]
I just checked, and left you a comment on it. Thanks for the issue and the PR, I need to investigate a little more about it, to try to make it work in as many versions of the emulator as possible.

**Comment by pangolp** [comment]
The PR has already been merged, thank you.
